<a href="https://colab.research.google.com/github/Parthpatil294/ML_6D_1BM23CS227/blob/main/LAB7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving iris (2).csv to iris (2).csv


In [ ]:
data = pd.read_csv('iris (2).csv')

data.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [ ]:
X = data.drop('species', axis=1)   # features
y = data['species']                # target

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

In [ ]:
rf = RandomForestClassifier(n_estimators=10, random_state=42)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy with 10 trees:", accuracy)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy with 10 trees: 1.0
Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [ ]:
best_score = 0
best_trees = 0

for n in range(1,101):

    model = RandomForestClassifier(n_estimators=n, random_state=42)
    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    score = accuracy_score(y_test, pred)

    if score > best_score:
        best_score = score
        best_trees = n

print("Best Accuracy:", best_score)
print("Best Number of Trees:", best_trees)

Best Accuracy: 1.0
Best Number of Trees: 1


In [ ]:
best_model = RandomForestClassifier(n_estimators=best_trees, random_state=42)

best_model.fit(X_train, y_train)

best_pred = best_model.predict(X_test)

print("Confusion Matrix for Best Model:")
print(confusion_matrix(y_test, best_pred))

Confusion Matrix for Best Model:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
